# Generated by Django 4.1.5 on 2023-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friendshipRequests',
        ),
        migrations.AddField(
            model_name='profile',
            name='friendshipRequestsSent',
            field=models.ManyToManyField(related_name='friendshipRequestsReceived', to='core.profile'),
        ),
    ]
