# Generated by Django 4.1.5 on 2023-01-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_friendshiprequests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatType',
            field=models.IntegerField(choices=[(1, 'PRIVATE'), (2, 'GROUP'), (3, 'COMMUNITY')]),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat', max_length=255),
        ),
    ]
