# Generated by Django 4.1.5 on 2023-01-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chat_chattype_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatType',
            field=models.IntegerField(choices=[(1, 'PRIVATE'), (2, 'GROUP')]),
        ),
    ]
